codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 95%
        threshold: 2%
        if_not_found: success
    
    patch:
      default:
        target: 90%
        threshold: 5%
        if_not_found: success

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "**/*.test.ts"
  - "**/*.spec.ts"
  - "**/setup.ts"
  - "e2e/**"
  - "playwright.config.ts"
  - "vitest.config.ts"
  - "astro.config.mjs"
  - "eslint.config.mjs"
  - "prettier.config.mjs"
