import type { ShelfData } from "@/types/content";

export const shelf: ShelfData = {
  physical: [
    { title: "1984", author: "George Orwell", sortName: "Orwell, George" },
    {
      title: "2001: una odisea espacial",
      author: "Arthur C. Clarke",
      sortName: "Clarke, Arthur C.",
      series: "Odisea del espacio",
      seriesOrder: 1,
    },
    {
      title: "Alicia en el país de las maravillas",
      author: "Lewis Carroll",
      sortName: "Carroll, Lewis",
      series: "Alicia",
      seriesOrder: 1,
    },
    { title: "Apocalipsis", author: "Stephen King", sortName: "King, Stephen" },
    { title: "Aquella casa maldita en Amityville", author: "Carlos Cala", sortName: "Cala, Carlos" },
    { title: "Buick 8: un coche perverso", author: "Stephen King", sortName: "King, Stephen" },
    { title: "Caja negra", author: "Francisco Narla", sortName: "Narla, Francisco" },
    { title: "Cementerio de animales", author: "Stephen King", sortName: "King, Stephen" },
    {
      title: "Crimen en directo",
      author: "Camilla Läckberg",
      sortName: "Läckberg, Camilla",
      series: "Fjällbacka",
      seriesOrder: 4,
    },
    { title: "Crónica de una muerte anunciada", author: "Gabriel García Márquez", sortName: "García Márquez, Gabriel" },
    { title: "Cuernos", author: "Joe Hill", sortName: "Hill, Joe" },
    { title: "Cujo", author: "Stephen King", sortName: "King, Stephen" },
    { title: "Dolores Claiborne", author: "Stephen King", sortName: "King, Stephen" },
    { title: "Don Quijote de la Mancha", author: "Miguel de Cervantes", sortName: "Cervantes, Miguel de" },
    { title: "Drácula", author: "Bram Stoker", sortName: "Stoker, Bram" },
    { title: "El bosque de los inocentes", author: "Graziella Moreno", sortName: "Moreno, Graziella" },
    { title: "El cazador de sueños", author: "Stephen King", sortName: "King, Stephen" },
    { title: "El club Dumas", author: "Arturo Pérez-Reverte", sortName: "Pérez-Reverte, Arturo" },
    { title: "El cumpleaños secreto", author: "Kate Morton", sortName: "Morton, Kate" },
    {
      title: "El extraño caso del Dr. Jekyll y Mr. Hyde",
      author: "Robert Louis Stevenson",
      sortName: "Stevenson, Robert Louis",
    },
    { title: "El fugitivo", author: "Stephen King", sortName: "King, Stephen" },
    {
      title: "El libro prohibido",
      author: "Christian Jacq",
      sortName: "Jacq, Christian",
      series: "Los misterios de Setna",
      seriesOrder: 2,
    },
    { title: "El maestro de esgrima", author: "Arturo Pérez-Reverte", sortName: "Pérez-Reverte, Arturo" },
    {
      title: "El misterioso caso de Styles",
      author: "Agatha Christie",
      sortName: "Christie, Agatha",
      series: "Hércule Poirot",
      seriesOrder: 1,
    },
    {
      title: "El pistolero",
      author: "Stephen King",
      sortName: "King, Stephen",
      series: "La Torre Oscura",
      seriesOrder: 1,
    },
    { title: "El principito", author: "Antoine de Saint-Exupéry", sortName: "Saint-Exupéry, Antoine de" },
    {
      title: "El prisionero del cielo",
      author: "Carlos Ruiz Zafón",
      sortName: "Ruiz Zafón, Carlos",
      series: "El Cementerio de los Libros Olvidados",
      seriesOrder: 3,
    },
    {
      title: "El resplandor",
      author: "Stephen King",
      sortName: "King, Stephen",
      series: "El Resplandor",
      seriesOrder: 1,
    },
    {
      title: "El retorno del rey",
      author: "J. R. R. Tolkien",
      sortName: "Tolkien, J. R. R.",
      series: "El Señor de los Anillos",
      seriesOrder: 3,
    },
    { title: "El retrato de Rose Madder", author: "Stephen King", sortName: "King, Stephen" },
    { title: "El señor de las moscas", author: "William Golding", sortName: "Golding, William" },
    {
      title: "El silencio de la ciudad blanca",
      author: "Eva García Sáenz de Urturi",
      sortName: "García Sáenz de Urturi, Eva",
      series: "La Ciudad Blanca",
      seriesOrder: 1,
    },
    {
      title: "El talento de Mr. Ripley",
      author: "Patricia Highsmith",
      sortName: "Highsmith, Patricia",
      series: "Ripley",
      seriesOrder: 1,
    },
    { title: "Espía de Dios", author: "Juan Gómez-Jurado", sortName: "Gómez-Jurado, Juan" },
    { title: "Frankenstein", author: "Mary Shelley", sortName: "Shelley, Mary" },
    { title: "Fulgor", author: "Manel Loureiro", sortName: "Loureiro, Manel" },
    {
      title: "La ciudad perdida",
      author: "Clive Cussler",
      sortName: "Cussler, Clive",
      series: "NUMA Files",
      seriesOrder: 5,
    },
    {
      title: "La comunidad del anillo",
      author: "J. R. R. Tolkien",
      sortName: "Tolkien, J. R. R.",
      series: "El Señor de los Anillos",
      seriesOrder: 1,
    },
    {
      title: "La corte de los espejos",
      author: "Concepción Perea",
      sortName: "Perea, Concepción",
      series: "La corte de los espejos",
      seriesOrder: 1,
    },
    {
      title: "La guerra civil contada a los jóvenes",
      author: "Arturo Pérez-Reverte",
      sortName: "Pérez-Reverte, Arturo",
    },
    { title: "La isla de Alice", author: "Daniel Sánchez Arévalo", sortName: "Sánchez Arévalo, Daniel" },
    {
      title: "La llegada de los tres",
      author: "Stephen King",
      sortName: "King, Stephen",
      series: "La Torre Oscura",
      seriesOrder: 2,
    },
    {
      title: "La plata de Britania",
      author: "Lindsey Davis",
      sortName: "Davis, Lindsey",
      series: "Marco Didio Falco",
      seriesOrder: 1,
    },
    {
      title: "La princesa de hielo",
      author: "Camilla Läckberg",
      sortName: "Läckberg, Camilla",
      series: "Fjällbacka",
      seriesOrder: 1,
    },
    { title: "La tabla de Flandes", author: "Arturo Pérez-Reverte", sortName: "Pérez-Reverte, Arturo" },
    {
      title: "La tumba maldita",
      author: "Christian Jacq",
      sortName: "Jacq, Christian",
      series: "Los misterios de Setna",
      seriesOrder: 1,
    },
    { title: "Las cuatro después de medianoche", author: "Stephen King", sortName: "King, Stephen" },
    { title: "Las dos después de medianoche", author: "Stephen King", sortName: "King, Stephen" },
    {
      title: "Las dos torres",
      author: "J. R. R. Tolkien",
      sortName: "Tolkien, J. R. R.",
      series: "El Señor de los Anillos",
      seriesOrder: 2,
    },
    {
      title: "Las hijas del frío",
      author: "Camilla Läckberg",
      sortName: "Läckberg, Camilla",
      series: "Fjällbacka",
      seriesOrder: 3,
    },
    { title: "Leyendas", author: "Gustavo Adolfo Bécquer", sortName: "Bécquer, Gustavo Adolfo" },
    { title: "Lolita", author: "Vladímir Nabókov", sortName: "Nabókov, Vladímir" },
    {
      title: "Los buenos suicidas",
      author: "Toni Hill",
      sortName: "Hill, Toni",
      series: "Inspector Salgado",
      seriesOrder: 2,
    },
    {
      title: "Los gritos del pasado",
      author: "Camilla Läckberg",
      sortName: "Läckberg, Camilla",
      series: "Fjällbacka",
      seriesOrder: 2,
    },
    {
      title: "Los guardianes de la historia",
      author: "Elisabetta Cametti",
      sortName: "Cametti, Elisabetta",
      series: "Katherine Sinclaire",
      seriesOrder: 1,
    },
    {
      title: "Los hombres que no amaban a las mujeres",
      author: "Stieg Larsson",
      sortName: "Larsson, Stieg",
      series: "Millennium",
      seriesOrder: 1,
    },
    {
      title: "La chica que soñaba con una cerilla y un bidón de gasolina",
      author: "Stieg Larsson",
      sortName: "Larsson, Stieg",
      series: "Millennium",
      seriesOrder: 2,
    },
    {
      title: "La reina en el palacio de las corrientes de aire",
      author: "Stieg Larsson",
      sortName: "Larsson, Stieg",
      series: "Millennium",
      seriesOrder: 3,
    },
    {
      title: "Los pilares de la Tierra",
      author: "Ken Follett",
      sortName: "Follett, Ken",
      series: "Kingsbridge",
      seriesOrder: 1,
    },
    {
      title: "Los ritos del agua",
      author: "Eva García Sáenz de Urturi",
      sortName: "García Sáenz de Urturi, Eva",
      series: "La Ciudad Blanca",
      seriesOrder: 2,
    },
    { title: "Macbeth", author: "William Shakespeare", sortName: "Shakespeare, William" },
    { title: "Memento de difuntos", author: "Andreu Martin", sortName: "Martin, Andreu" },
    { title: "Mind the gap", author: "Nacho Iribarnegaray", sortName: "Iribarnegaray, Nacho" },
    { title: "Misery", author: "Stephen King", sortName: "King, Stephen" },
    { title: "No confíes en nadie", author: "S. J. Watson", sortName: "Watson, S. J." },
    { title: "Oscuro", author: "Teo Rodríguez", sortName: "Rodríguez, Teo" },
    { title: "Otra vida", author: "S. J. Watson", sortName: "Watson, S. J." },
    { title: "Peter Pan", author: "James M. Barrie", sortName: "Barrie, James M." },
    { title: "Pronto será de noche", author: "Jesús Cañadas", sortName: "Cañadas, Jesús" },
    { title: "Pídele papeles a Santa Simpa", author: "Martín Zeke Ochoa", sortName: "Zeke Ochoa, Martín" },
    { title: "Rebeca", author: "Daphne du Maurier", sortName: "du Maurier, Daphne" },
    { title: "Revival", author: "Stephen King", sortName: "King, Stephen" },
    { title: "Tienes hasta las 10", author: "Francisco Castro", sortName: "Castro, Francisco" },
    { title: "Tirant lo blanch (I)", author: "Joanot Martorell", sortName: "Martorell, Joanot" },
    { title: "Tirant lo blanch (II)", author: "Joanot Martorell", sortName: "Martorell, Joanot" },
    { title: "Todo esto te daré", author: "Dolores Redondo", sortName: "Redondo, Dolores" },
    { title: "Trilogía de la Fundación", author: "Isaac Asimov", sortName: "Asimov, Isaac" },
    { title: "Fundación", author: "Isaac Asimov", sortName: "Asimov, Isaac", series: "Fundación", seriesOrder: 1 },
    {
      title: "Fundación e Imperio",
      author: "Isaac Asimov",
      sortName: "Asimov, Isaac",
      series: "Fundación",
      seriesOrder: 2,
    },
    {
      title: "Segunda Fundación",
      author: "Isaac Asimov",
      sortName: "Asimov, Isaac",
      series: "Fundación",
      seriesOrder: 3,
    },
    {
      title: "Los límites de la Fundación",
      author: "Isaac Asimov",
      sortName: "Asimov, Isaac",
      series: "Fundación",
      seriesOrder: 4,
    },
    { title: "Un puñado de amigos y dos cerezas", author: "Rosa Grau", sortName: "Grau, Rosa" },
    { title: "Yo, robot", author: "Isaac Asimov", sortName: "Asimov, Isaac" },
    { title: "Némesis", author: "Isaac Asimov", sortName: "Asimov, Isaac" },
    { title: "El señor de los anillos", author: "J. R. R. Tolkien", sortName: "Tolkien, J. R. R." },
    {
      title: "Cuentos inconclusos de Númenor y la Tierra Media",
      author: "J. R. R. Tolkien",
      sortName: "Tolkien, J. R. R.",
    },
    { title: "El hobbit", author: "J. R. R. Tolkien", sortName: "Tolkien, J. R. R." },
    { title: "El Silmarillion", author: "J. R. R. Tolkien", sortName: "Tolkien, J. R. R." },
    { title: "Los hijos de Húrin", author: "J. R. R. Tolkien", sortName: "Tolkien, J. R. R." },
    { title: "Las leyendas del anillo de Tolkien", author: "David Day", sortName: "Day, David" },
    { title: "Un atlas de Tolkien", author: "David Day", sortName: "Day, David" },
    { title: "El infiltrado", author: "Marta Querol", sortName: "Querol, Marta" },
    {
      title: "La leyenda de Drizzt: El elfo oscuro",
      author: "R. A. Salvatore",
      sortName: "Salvatore, R. A.",
      series: "La Leyenda de Drizzt",
      seriesOrder: 1,
    },
    {
      title: "Harry Potter y la piedra filosofal",
      author: "J. K. Rowling",
      sortName: "Rowling, J. K.",
      series: "Harry Potter",
      seriesOrder: 1,
    },
    {
      title: "Harry Potter y la cámara secreta",
      author: "J. K. Rowling",
      sortName: "Rowling, J. K.",
      series: "Harry Potter",
      seriesOrder: 2,
    },
    {
      title: "Harry Potter y el prisionero de Azkaban",
      author: "J. K. Rowling",
      sortName: "Rowling, J. K.",
      series: "Harry Potter",
      seriesOrder: 3,
    },
    {
      title: "Harry Potter y el cáliz de fuego",
      author: "J. K. Rowling",
      sortName: "Rowling, J. K.",
      series: "Harry Potter",
      seriesOrder: 4,
    },
    {
      title: "Harry Potter y la Orden del Fénix",
      author: "J. K. Rowling",
      sortName: "Rowling, J. K.",
      series: "Harry Potter",
      seriesOrder: 5,
    },
    {
      title: "Harry Potter y el misterio del príncipe",
      author: "J. K. Rowling",
      sortName: "Rowling, J. K.",
      series: "Harry Potter",
      seriesOrder: 6,
    },
    {
      title: "Harry Potter y las reliquias de la Muerte",
      author: "J. K. Rowling",
      sortName: "Rowling, J. K.",
      series: "Harry Potter",
      seriesOrder: 7,
    },
    { title: "Animales fantásticos y dónde encontrarlos", author: "J. K. Rowling", sortName: "Rowling, J. K." },
    { title: "El Ickabog", author: "J. K. Rowling", sortName: "Rowling, J. K." },
    { title: "Harry Potter y el legado maldito", author: "Jack Thorne", sortName: "Thorne, Jack" },
    {
      title: "Seis grullas",
      author: "Elizabeth Lim",
      sortName: "Lim, Elizabeth",
      series: "Seis grullas",
      seriesOrder: 1,
    },
    {
      title: "Indumentaria valenciana: siglos XVIII-XIX",
      author: "M.ª Victoria Liceras",
      sortName: "Liceras, M.ª Victoria",
    },
    {
      title: "A la moda valenciana: l'home al segle XVIII",
      author: "Salvador Mercado Machí",
      sortName: "Mercado Machí, Salvador",
    },
    {
      title: "A la moda valenciana: la dona al segle XVIII",
      author: "Salvador Mercado Machí",
      sortName: "Mercado Machí, Salvador",
    },
    {
      title: "Indumentària valenciana al detall",
      author: "Francesc Xavier Rausell Adrian",
      sortName: "Rausell Adrian, Francesc Xavier",
    },
    { title: "Cent anys d'indumentaria tradicional", author: "Paquita Roca", sortName: "Roca, Paquita" },
    { title: "Torrent i la seua indumentària", author: "Àngel Martínez Aparisi", sortName: "Martínez Aparisi, Àngel" },
    {
      title: "Juego de tronos",
      author: "George R. R. Martin",
      sortName: "Martin, George R. R.",
      series: "Canción de Hielo y Fuego",
      seriesOrder: 1,
    },
    {
      title: "Choque de reyes",
      author: "George R. R. Martin",
      sortName: "Martin, George R. R.",
      series: "Canción de Hielo y Fuego",
      seriesOrder: 2,
    },
    {
      title: "Tormenta de espadas",
      author: "George R. R. Martin",
      sortName: "Martin, George R. R.",
      series: "Canción de Hielo y Fuego",
      seriesOrder: 3,
    },
    {
      title: "Festín de cuervos",
      author: "George R. R. Martin",
      sortName: "Martin, George R. R.",
      series: "Canción de Hielo y Fuego",
      seriesOrder: 4,
    },
    {
      title: "Danza de dragones",
      author: "George R. R. Martin",
      sortName: "Martin, George R. R.",
      series: "Canción de Hielo y Fuego",
      seriesOrder: 5,
    },
    {
      title: "El imperio final",
      author: "Brandon Sanderson",
      sortName: "Sanderson, Brandon",
      series: "Nacidos de la Bruma",
      seriesOrder: 1,
    },
    {
      title: "El pozo de la ascensión",
      author: "Brandon Sanderson",
      sortName: "Sanderson, Brandon",
      series: "Nacidos de la Bruma",
      seriesOrder: 2,
    },
    {
      title: "El héroe de las eras",
      author: "Brandon Sanderson",
      sortName: "Sanderson, Brandon",
      series: "Nacidos de la Bruma",
      seriesOrder: 3,
    },
    {
      title: "Ángeles y demonios",
      author: "Dan Brown",
      sortName: "Brown, Dan",
      series: "Robert Langdon",
      seriesOrder: 1,
    },
    {
      title: "El código Da Vinci",
      author: "Dan Brown",
      sortName: "Brown, Dan",
      series: "Robert Langdon",
      seriesOrder: 2,
    },
    {
      title: "El símbolo perdido",
      author: "Dan Brown",
      sortName: "Brown, Dan",
      series: "Robert Langdon",
      seriesOrder: 3,
    },
    { title: "Inferno", author: "Dan Brown", sortName: "Brown, Dan", series: "Robert Langdon", seriesOrder: 4 },
    {
      title: "Divina Comedia: Infierno",
      author: "Dante Alighieri",
      sortName: "Alighieri, Dante",
      series: "Divina Comedia",
      seriesOrder: 1,
    },
    { title: "La extraordinaria historia de Jaime I el conquistador", author: "J. R. Barat", sortName: "Barat, J. R." },
    { title: "1707", author: "J. R. Barat", sortName: "Barat, J. R." },
    { title: "Història de Valéncia en pindoletes", author: "José Vilaseca", sortName: "Vilaseca, José" },
    { title: "Historia inventada de Cataluña", author: "José Vilaseca", sortName: "Vilaseca, José" },
    { title: "Historia del Reino de Valencia en pildoritas", author: "José Vilaseca", sortName: "Vilaseca, José" },
    { title: "Crónicas de Balansiya", author: "José Carlos Grau Enguita", sortName: "Grau Enguita, José Carlos" },
    {
      title: "En busca del león verde",
      author: "Judith Merkle Riley",
      sortName: "Merkle Riley, Judith",
      series: "Margaret de Ashbury",
      seriesOrder: 2,
    },
    {
      title: "Arturo: La piedra de la leyenda",
      author: "Kevin Crossley-Holland",
      sortName: "Crossley-Holland, Kevin",
      series: "Trilogía de Arturo",
      seriesOrder: 1,
    },
    { title: "Pompeya", author: "Robert Harris", sortName: "Harris, Robert" },
    {
      title: "Los 100",
      author: "Kass Morgan",
      sortName: "Morgan, Kass",
      series: "Los 100",
      seriesOrder: 1,
    },
    { title: "Muro de escudos", author: "Justin Hill", sortName: "Hill, Justin" },
    { title: "Las lágrimas de Julio César", author: "Jesús Maeso de la Torre", sortName: "Maeso de la Torre, Jesús" },
    {
      title: "Africanus",
      author: "Santiago Posteguillo",
      sortName: "Posteguillo, Santiago",
      series: "Trilogía Africanus",
      seriesOrder: 1,
    },
    {
      title: "Sinsajo",
      author: "Suzanne Collins",
      sortName: "Collins, Suzanne",
      series: "Los Juegos del Hambre",
      seriesOrder: 3,
    },
    { title: "20 pasos hacia adelante", author: "Jorge Bucay", sortName: "Bucay, Jorge" },
    { title: "Las 3 preguntas", author: "Jorge Bucay", sortName: "Bucay, Jorge" },
    { title: "De la autoestima al egoísmo", author: "Jorge Bucay", sortName: "Bucay, Jorge" },
    { title: "El mito de la diosa fortuna", author: "Jorge Bucay", sortName: "Bucay, Jorge" },
    { title: "Cuenta conmigo", author: "Jorge Bucay", sortName: "Bucay, Jorge" },
    { title: "Amarse con los ojos abiertos", author: "Jorge Bucay", sortName: "Bucay, Jorge" },
    { title: "Cuentos clásicos para conocerte mejor", author: "Jorge Bucay", sortName: "Bucay, Jorge" },
    { title: "El juego de los cuentos", author: "Jorge Bucay", sortName: "Bucay, Jorge" },
    { title: "Bienestar, autoestima y felicidad", author: "Raimon Gaja", sortName: "gaja, Raimon" },
    { title: "El alquimista", author: "Paulo Coelho", sortName: "Coelho, Paulo" },
    {
      title: "El nombre del viento",
      author: "Patrick Rothfuss",
      sortName: "Rothfuss, Patrick",
      series: "Crónica del Asesino de Reyes",
      seriesOrder: 1,
    },
    {
      title: "El temor de un hombre sabio",
      author: "Patrick Rothfuss",
      sortName: "Rothfuss, Patrick",
      series: "Crónica del Asesino de Reyes",
      seriesOrder: 2,
    },
    {
      title: "La música del silencio",
      author: "Patrick Rothfuss",
      sortName: "Rothfuss, Patrick",
      series: "Crónica del Asesino de Reyes",
    },
    {
      title: "El estrecho sendero entre deseos",
      author: "Patrick Rothfuss",
      sortName: "Rothfuss, Patrick",
      series: "Crónica del Asesino de Reyes",
    },
    { title: "Cuentos escogidos", author: "Edgar Allan Poe", sortName: "Poe, Edgar Allan" },
    {
      title: "El reinado inmortal",
      author: "Morgan Rhodes",
      sortName: "Rhodes, Morgan",
      series: "La Caída de los Reinos",
      seriesOrder: 6,
    },
    { title: "Los mitos eternos", author: "Pol Gise", sortName: "Gise, Pol" },
    { title: "Némesis", author: "Sebastián Roa", sortName: "Roa, Sebastián" },
    {
      title: "El ladrón de las sombras",
      author: "Alexey Pehov",
      sortName: "Pehov, Alexey",
      series: "Crónicas de Siala",
      seriesOrder: 1,
    },
    { title: "Los mártires de Arjona", author: "Juan Eslava Galán", sortName: "Eslava Galán, Juan" },
    { title: "Aquitania", author: "Eva García Sáenz de Urturi", sortName: "García Sáenz de Urturi, Eva" },
    { title: "Gran historia visual de la filosofía", author: "Masato Tanaka", sortName: "Tanaka, Masato" },
    { title: "El mundo de Sofía", author: "Jostein Gaarder", sortName: "Gaarder, Jostein" },
    { title: "Antología de leyendas portuguesas", author: "Alexandre Parafita", sortName: "Parafita, Alexandre" },
    { title: "Edda menor", author: "Snorri Sturluson", sortName: "Sturluson, Snorri" },
    { title: "Los hilos de la traición", author: "Daniel Casado Lara", sortName: "Casado Lara, Daniel" },
    {
      title: "Trece runas",
      author: "Michael Peinkofer",
      sortName: "Peinkofer, Michael",
      series: "Trece runas",
      seriesOrder: 1,
    },
    { title: "Ciro, el grande", author: "Harold Lamb", sortName: "Lamb, Harold" },
  ],
  digital: [],
};
