import type { ShelfData } from "@/types/content";

export const shelf: ShelfData = {
  physical: [
    { title: "1984", author: "George Orwell", sortName: "Orwell, George" },
    { title: "2001: una odisea espacial", author: "Arthur C. Clarke", sortName: "Clarke, Arthur C." },
    { title: "Alicia en el país de las maravillas", author: "Lewis Carroll", sortName: "Carroll, Lewis" },
    { title: "Apocalipsis", author: "Stephen King", sortName: "King, Stephen" },
    { title: "Aquella casa maldita en Amityville", author: "Carlos Cala", sortName: "Cala, Carlos" },
    { title: "Buick 8: un coche perverso", author: "Stephen King", sortName: "King, Stephen" },
    { title: "Caja negra", author: "Francisco Narla", sortName: "Narla, Francisco" },
    { title: "Cementerio de animales", author: "Stephen King", sortName: "King, Stephen" },
    { title: "Crimen en directo", author: "Camilla Läckberg", sortName: "Läckberg, Camilla" },
    { title: "Crónica de una muerte anunciada", author: "Gabriel García Márquez", sortName: "García Márquez, Gabriel" },
    { title: "Cuernos", author: "Joe Hill", sortName: "Hill, Joe" },
    { title: "Cujo", author: "Stephen King", sortName: "King, Stephen" },
    { title: "Dolores Claiborne", author: "Stephen King", sortName: "King, Stephen" },
    { title: "Don Quijote de la Mancha", author: "Miguel de Cervantes", sortName: "Cervantes, Miguel de" },
    { title: "Drácula", author: "Bram Stoker", sortName: "Stoker, Bram" },
    { title: "El bosque de los inocentes", author: "Graziella Moreno", sortName: "Moreno, Graziella" },
    { title: "El cazador de sueños", author: "Stephen King", sortName: "King, Stephen" },
    { title: "El club Dumas", author: "Arturo Pérez-Reverte", sortName: "Pérez-Reverte, Arturo" },
    { title: "El cumpleaños secreto", author: "Kate Morton", sortName: "Morton, Kate" },
    {
      title: "El extraño caso del Dr. Jekyll y Mr. Hyde",
      author: "Robert Louis Stevenson",
      sortName: "Stevenson, Robert Louis",
    },
    { title: "El fugitivo", author: "Stephen King", sortName: "King, Stephen" },
    { title: "El libro prohibido", author: "Christian Jacq", sortName: "Jacq, Christian" },
    { title: "El maestro de esgrima", author: "Arturo Pérez-Reverte", sortName: "Pérez-Reverte, Arturo" },
    { title: "El misterioso caso de Styles", author: "Agatha Christie", sortName: "Christie, Agatha" },
    { title: "El pistolero", author: "Stephen King", sortName: "King, Stephen" },
    { title: "El principito", author: "Antoine de Saint-Exupéry", sortName: "Saint-Exupéry, Antoine de" },
    { title: "El prisionero del cielo", author: "Carlos Ruiz Zafón", sortName: "Ruiz Zafón, Carlos" },
    { title: "El resplandor", author: "Stephen King", sortName: "King, Stephen" },
    { title: "El retorno del rey", author: "J. R. R. Tolkien", sortName: "Tolkien, J. R. R." },
    { title: "El retrato de Rose Madder", author: "Stephen King", sortName: "King, Stephen" },
    { title: "El señor de las moscas", author: "William Golding", sortName: "Golding, William" },
    {
      title: "El silencio de la ciudad blanca",
      author: "Eva García Sáenz de Urturi",
      sortName: "García Sáenz de Urturi, Eva",
    },
    { title: "El talento de Mr. Ripley", author: "Patricia Highsmith", sortName: "Highsmith, Patricia" },
    { title: "Espía de Dios", author: "Juan Gómez-Jurado", sortName: "Gómez-Jurado, Juan" },
    { title: "Frankenstein", author: "Mary Shelley", sortName: "Shelley, Mary" },
    { title: "Fulgor", author: "Manel Loureiro", sortName: "Loureiro, Manel" },
    { title: "La ciudad perdida", author: "Clive Cussler", sortName: "Cussler, Clive" },
    { title: "La comunidad del anillo", author: "J. R. R. Tolkien", sortName: "Tolkien, J. R. R." },
    { title: "La corte de los espejos", author: "Concepción Perea", sortName: "Perea, Concepción" },
    {
      title: "La guerra civil contada a los jóvenes",
      author: "Arturo Pérez-Reverte",
      sortName: "Pérez-Reverte, Arturo",
    },
    { title: "La isla de Alice", author: "Daniel Sánchez Arévalo", sortName: "Sánchez Arévalo, Daniel" },
    { title: "La llegada de los tres", author: "Stephen King", sortName: "King, Stephen" },
    { title: "La princesa de hielo", author: "Camilla Läckberg", sortName: "Läckberg, Camilla" },
    { title: "La tabla de Flandes", author: "Arturo Pérez-Reverte", sortName: "Pérez-Reverte, Arturo" },
    { title: "La tumba maldita", author: "Christian Jacq", sortName: "Jacq, Christian" },
    { title: "Las cuatro después de medianoche", author: "Stephen King", sortName: "King, Stephen" },
    { title: "Las dos después de medianoche", author: "Stephen King", sortName: "King, Stephen" },
    { title: "Las dos torres", author: "J. R. R. Tolkien", sortName: "Tolkien, J. R. R." },
    { title: "Las hijas del frío", author: "Camilla Läckberg", sortName: "Läckberg, Camilla" },
    { title: "Leyendas", author: "Gustavo Adolfo Bécquer", sortName: "Bécquer, Gustavo Adolfo" },
    { title: "Lolita", author: "Vladímir Nabókov", sortName: "Nabókov, Vladímir" },
    { title: "Los buenos suicidas", author: "Toni Hill", sortName: "Hill, Toni" },
    { title: "Los gritos del pasado", author: "Camilla Läckberg", sortName: "Läckberg, Camilla" },
    { title: "Los guardianes de la historia", author: "Elisabetta Cametti", sortName: "Cametti, Elisabetta" },
    { title: "Los hombres que no amaban a las mujeres", author: "Stieg Larsson", sortName: "Larsson, Stieg" },
    { title: "Los pilares de la Tierra", author: "Ken Follett", sortName: "Follett, Ken" },
    { title: "Los ritos del agua", author: "Eva García Sáenz de Urturi", sortName: "García Sáenz de Urturi, Eva" },
    { title: "Macbeth", author: "William Shakespeare", sortName: "Shakespeare, William" },
    { title: "Memento de difuntos", author: "Andreu Martin", sortName: "Martin, Andreu" },
    { title: "Mind the gap", author: "Nacho Iribarnegaray", sortName: "Iribarnegaray, Nacho" },
    { title: "Misery", author: "Stephen King", sortName: "King, Stephen" },
    { title: "No confíes en nadie", author: "S. J. Watson", sortName: "Watson, S. J." },
    { title: "Oscuro", author: "Teo Rodríguez", sortName: "Rodríguez, Teo" },
    { title: "Otra vida", author: "S. J. Watson", sortName: "Watson, S. J." },
    { title: "Peter Pan", author: "James M. Barrie", sortName: "Barrie, James M." },
    { title: "Pronto será de noche", author: "Jesús Cañadas", sortName: "Cañadas, Jesús" },
    { title: "Pídele papeles a Santa Simpa", author: "Martín Zeke Ochoa", sortName: "Zeke Ochoa, Martín" },
    { title: "Rebeca", author: "Daphne du Maurier", sortName: "du Maurier, Daphne" },
    { title: "Revival", author: "Stephen King", sortName: "King, Stephen" },
    { title: "Tienes hasta las 10", author: "Francisco Castro", sortName: "Castro, Francisco" },
    { title: "Tirant lo blanch (I)", author: "Joanot Martorell", sortName: "Martorell, Joanot" },
    { title: "Tirant lo blanch (i II)", author: "Joanot Martorell", sortName: "Martorell, Joanot" },
    { title: "Todo esto te daré", author: "Dolores Redondo", sortName: "Redondo, Dolores" },
    { title: "Trilogía de la Fundación", author: "Isaac Asimov", sortName: "Asimov, Isaac" },
    { title: "Un puñado de amigos y dos cerezas", author: "Rosa Grau", sortName: "Grau, Rosa" },
    { title: "Yo, robot", author: "Isaac Asimov", sortName: "Asimov, Isaac" },
  ],
  digital: [],
};
