/**
 * Static Image Imports
 *
 * This file contains all static image imports for build-time optimization.
 * Astro's image optimization only works with imported images, not string paths.
 *
 * ⚠️  AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: scripts/generate-image-imports.ts
 * Generated at: 2026-01-05T20:17:50.509Z
 *
 * To regenerate this file:
 *   bun run generate:images
 *
 * When adding new images:
 * 1. Place the image in src/assets/[category]/ (books, authors, tutorials, posts, defaults)
 * 2. Run: bun run generate:images
 * 3. Build: bun run build (Astro will optimize automatically)
 */

import type { ImageMetadata } from "astro";

// ============================================================================
// BOOK COVER IMAGES
// ============================================================================

import camillaLackberg from "@/assets/authors/camilla-lackberg.jpg";
import charlesDickens from "@/assets/authors/charles-dickens.jpg";
import doloresRedondo from "@/assets/authors/dolores-redondo.jpg";
import stephenKing from "@/assets/authors/stephen-king.jpg";
import apocalipsisStephenKing from "@/assets/books/apocalipsis-stephen-king.jpg";
import area81StephenKing from "@/assets/books/area-81-stephen-king.jpg";
import carrieStephenKing from "@/assets/books/carrie-stephen-king.jpg";
import cuentosNavidadDickens from "@/assets/books/cuentos-navidad-dickens.jpg";
import elCicloDelHombreLoboStephenKing from "@/assets/books/el-ciclo-del-hombre-lobo-stephen-king.jpg";
import elMisterioDeSalemsLotStephenKing from "@/assets/books/el-misterio-de-salems-lot-stephen-king.jpg";
import elResplandorStephenKing from "@/assets/books/el-resplandor-stephen-king.jpg";
import elUmbralDeLaNocheStephenKing from "@/assets/books/el-umbral-de-la-noche-stephen-king.jpg";
import laPrincesaDeHielo from "@/assets/books/la-princesa-de-hielo.jpg";
import mrMercedesStephenKing from "@/assets/books/mr-mercedes-stephen-king.jpg";
import rabiaStephenKing from "@/assets/books/rabia-stephen-king.jpg";
import revivalStephenKing from "@/assets/books/revival-stephen-king.jpg";
import theStandStephenKing from "@/assets/books/the-stand-stephen-king.jpg";
import todoEstoTeDare from "@/assets/books/todo-esto-te-dare.jpg";
// ============================================================================
// AUTHOR PICTURE IMAGES
// ============================================================================

// ============================================================================
// DEFAULT IMAGES
// ============================================================================

import bookDefaultEn from "@/assets/defaults/book-default-en.jpg";
import bookDefaultEs from "@/assets/defaults/book-default-es.jpg";
import postDefault from "@/assets/defaults/post-default.jpg";
import tutorialDefault from "@/assets/defaults/tutorial-default.jpg";
import { getDefaultLanguageCode, type LanguageKey } from "@/config/languages";

/**
 * Book Cover Images Map
 *
 * Key: Image filename (without extension) - matches the filename in content frontmatter
 * Value: Imported ImageMetadata
 *
 * Usage:
 * ```astro
 * import { bookCovers } from '@/utils/imageImports';
 * <OptimizedImage src={bookCovers['apocalipsis-stephen-king']} alt="..." />
 * ```
 */
export const bookCovers: Record<string, ImageMetadata> = {
  "apocalipsis-stephen-king": apocalipsisStephenKing,
  "area-81-stephen-king": area81StephenKing,
  "carrie-stephen-king": carrieStephenKing,
  "cuentos-navidad-dickens": cuentosNavidadDickens,
  "el-ciclo-del-hombre-lobo-stephen-king": elCicloDelHombreLoboStephenKing,
  "el-misterio-de-salems-lot-stephen-king": elMisterioDeSalemsLotStephenKing,
  "el-resplandor-stephen-king": elResplandorStephenKing,
  "el-umbral-de-la-noche-stephen-king": elUmbralDeLaNocheStephenKing,
  "la-princesa-de-hielo": laPrincesaDeHielo,
  "mr-mercedes-stephen-king": mrMercedesStephenKing,
  "rabia-stephen-king": rabiaStephenKing,
  "revival-stephen-king": revivalStephenKing,
  "the-stand-stephen-king": theStandStephenKing,
  "todo-esto-te-dare": todoEstoTeDare,
};

/**
 * Author Picture Images Map
 *
 * Key: Image filename (without extension) - matches the filename in content frontmatter
 * Value: Imported ImageMetadata
 *
 * Usage:
 * ```astro
 * import { authorPictures } from '@/utils/imageImports';
 * <OptimizedImage src={authorPictures['camilla-lackberg']} alt="..." />
 * ```
 */
export const authorPictures: Record<string, ImageMetadata> = {
  "camilla-lackberg": camillaLackberg,
  "charles-dickens": charlesDickens,
  "dolores-redondo": doloresRedondo,
  "stephen-king": stephenKing,
};

/**
 * Default Images Map
 *
 * Fallback images when content doesn't specify a cover/picture
 *
 * Usage:
 * ```astro
 * import { defaultImages } from '@/utils/imageImports';
 * <OptimizedImage src={defaultImages.postDefault} alt="Default post cover" />
 * ```
 */
export const defaultImages = {
  bookDefaultEn,
  bookDefaultEs,
  postDefault,
  tutorialDefault,
};

/**
 * Tutorial Cover Images Map
 *
 * Key: Image filename (without extension) - matches the filename in content frontmatter
 * Value: Imported ImageMetadata
 *
 * Usage:
 * ```astro
 * import { tutorialCovers } from '@/utils/imageImports';
 * <OptimizedImage src={tutorialCovers['slug']} alt="..." />
 * ```
 */
export const tutorialCovers: Record<string, ImageMetadata> = {};

/**
 * Post Cover Images Map
 *
 * Key: Image filename (without extension) - matches the filename in content frontmatter
 * Value: Imported ImageMetadata
 *
 * Usage:
 * ```astro
 * import { postCovers } from '@/utils/imageImports';
 * <OptimizedImage src={postCovers['slug']} alt="..." />
 * ```
 */
export const postCovers: Record<string, ImageMetadata> = {};

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

/**
 * Get a book cover by filename (without path or extension)
 *
 * @param coverPath - Path from content frontmatter (e.g., "/images/books/example.jpg")
 * @param lang - Language for default cover fallback
 * @returns ImageMetadata for optimized rendering
 *
 * @example
 * const cover = getBookCoverImage('/images/books/example.jpg', 'es');
 * <OptimizedImage src={cover} alt="..." />
 */
export function getBookCoverImage(
  coverPath: string | undefined,
  lang: LanguageKey = getDefaultLanguageCode(),
): ImageMetadata {
  if (!coverPath) {
    return lang === getDefaultLanguageCode() ? defaultImages.bookDefaultEs : defaultImages.bookDefaultEn;
  }

  // Extract filename from path: "/images/books/el-hobbit.jpg" -> "el-hobbit"
  const filename = coverPath
    .split("/")
    .pop()
    ?.replace(/\.(jpg|jpeg|png|webp)$/i, "");

  if (!filename || !bookCovers[filename]) {
    console.warn(`Book cover not found: ${coverPath} (filename: ${filename})`);
    return lang === getDefaultLanguageCode() ? defaultImages.bookDefaultEs : defaultImages.bookDefaultEn;
  }

  return bookCovers[filename];
}

/**
 * Get a author picture by filename (without path or extension)
 *
 * @param picturePath - Path from content frontmatter (e.g., "/images/authors/example.jpg")
 * @returns ImageMetadata for optimized rendering
 *
 * @example
 * const picture = getAuthorPictureImage('/images/authors/example.jpg');
 * <OptimizedImage src={picture} alt="..." />
 */
export function getAuthorPictureImage(picturePath: string | undefined): ImageMetadata | undefined {
  if (!picturePath) {
    return undefined;
  }

  // If it's a full path, extract filename
  const slug = picturePath.includes("/")
    ? picturePath
        .split("/")
        .pop()
        ?.replace(/\.(jpg|jpeg|png|webp)$/i, "")
    : picturePath;

  if (!slug || !authorPictures[slug]) {
    console.warn(`Author picture not found: ${picturePath} (slug: ${slug})`);
    return undefined;
  }

  return authorPictures[slug];
}

/**
 * Get a tutorial cover by filename (without path or extension)
 *
 * @param coverPath - Path from content frontmatter (e.g., "/images/tutorials/example.jpg")
 * @returns ImageMetadata for optimized rendering
 *
 * @example
 * const cover = getTutorialCoverImage('/images/tutorials/example.jpg');
 * <OptimizedImage src={cover} alt="..." />
 */
export function getTutorialCoverImage(coverPath: string | undefined): ImageMetadata {
  if (!coverPath) {
    return defaultImages.tutorialDefault;
  }

  // Extract filename from path: "/images/books/el-hobbit.jpg" -> "el-hobbit"
  const filename = coverPath
    .split("/")
    .pop()
    ?.replace(/\.(jpg|jpeg|png|webp)$/i, "");

  if (!filename || !tutorialCovers[filename]) {
    console.warn(`Custom tutorials covers not yet implemented. Using default for: ${coverPath}`);
    return defaultImages.tutorialDefault;
  }

  return tutorialCovers[filename];
}

/**
 * Get a post cover by filename (without path or extension)
 *
 * @param coverPath - Path from content frontmatter (e.g., "/images/posts/example.jpg")
 * @returns ImageMetadata for optimized rendering
 *
 * @example
 * const cover = getPostCoverImage('/images/posts/example.jpg');
 * <OptimizedImage src={cover} alt="..." />
 */
export function getPostCoverImage(coverPath: string | undefined): ImageMetadata {
  if (!coverPath) {
    return defaultImages.postDefault;
  }

  // Extract filename from path: "/images/books/el-hobbit.jpg" -> "el-hobbit"
  const filename = coverPath
    .split("/")
    .pop()
    ?.replace(/\.(jpg|jpeg|png|webp)$/i, "");

  if (!filename || !postCovers[filename]) {
    console.warn(`Custom posts covers not yet implemented. Using default for: ${coverPath}`);
    return defaultImages.postDefault;
  }

  return postCovers[filename];
}

// ============================================================================
// UTILITIES
// ============================================================================

/**
 * Get all available book cover keys
 * Useful for validation or listing
 */
export function getAvailableBookCovers(): string[] {
  return Object.keys(bookCovers);
}

/**
 * Get all available author picture keys
 * Useful for validation or listing
 */
export function getAvailableAuthorPictures(): string[] {
  return Object.keys(authorPictures);
}

/**
 * Check if a book cover exists
 *
 * @param coverPath - Path or slug to check
 * @returns true if the cover exists in the imports
 */
export function hasBookCover(coverPath: string): boolean {
  const filename = coverPath
    .split("/")
    .pop()
    ?.replace(/\.(jpg|jpeg|png|webp)$/i, "");
  return !!filename && !!bookCovers[filename];
}

/**
 * Check if an author picture exists
 *
 * @param slug - Author slug to check
 * @returns true if the picture exists in the imports
 */
export function hasAuthorPicture(slug: string): boolean {
  const authorSlug = slug
    .split("/")
    .pop()
    ?.replace(/\.(jpg|jpeg|png|webp)$/i, "");
  return !!authorSlug && !!authorPictures[authorSlug];
}
