/**
 * Static Image Imports
 *
 * This file contains all static image imports for build-time optimization.
 * Astro's image optimization only works with imported images, not string paths.
 *
 * ⚠️  AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: scripts/generate-image-imports.ts
 * Generated at: 2026-02-20T20:17:42.313Z
 *
 * To regenerate this file:
 *   bun run generate:images
 *
 * When adding new images:
 * 1. Place the image in src/assets/[category]/ (books, authors, tutorials, posts, defaults)
 * 2. Run: bun run generate:images
 * 3. Build: bun run build (Astro will optimize automatically)
 */

// External imports
import type { ImageMetadata } from "astro";

// Internal imports

// Image imports (sorted alphabetically)
import agathaChristie from "@/assets/authors/agatha-christie.jpg";
import annaStarobinets from "@/assets/authors/anna-starobinets.jpg";
import camillaLackberg from "@/assets/authors/camilla-lackberg.jpg";
import charlesDickens from "@/assets/authors/charles-dickens.jpg";
import doloresRedondo from "@/assets/authors/dolores-redondo.jpg";
import evaGarciaSaenzDeUrturi from "@/assets/authors/eva-garcia-saenz-de-urturi.jpg";
import georgeOrwell from "@/assets/authors/george-orwell.jpg";
import isabelAllende from "@/assets/authors/isabel-allende.jpg";
import jKRowling from "@/assets/authors/j-k-rowling.jpg";
import jamesMBarrie from "@/assets/authors/james-m-barrie.jpg";
import karinBoye from "@/assets/authors/karin-boye.jpg";
import lauraGallego from "@/assets/authors/laura-gallego.jpg";
import martinZekeOchoa from "@/assets/authors/martin-zeke-ochoa.jpg";
import maryShelley from "@/assets/authors/mary-shelley.jpg";
import roaldDahl from "@/assets/authors/roald-dahl.jpg";
import stefanZweig from "@/assets/authors/stefan-zweig.jpg";
import stephenKing from "@/assets/authors/stephen-king.jpg";
import williamGolding from "@/assets/authors/william-golding.jpg";
import book1984DeGeorgeOrwell from "@/assets/books/1984-de-george-orwell.jpg";
import aliciaEnElPaisDeLasMaravillasLewisCarrollEdicionConmemorativa from "@/assets/books/alicia-en-el-pais-de-las-maravillas-lewis-carroll-edicion-conmemorativa.jpg";
import aliciaEnElPaisDeLasMaravillasLewisCarroll from "@/assets/books/alicia-en-el-pais-de-las-maravillas-lewis-carroll.jpg";
import apocalipsisDeStephenKing from "@/assets/books/apocalipsis-de-stephen-king.jpg";
import apocalipsisZDeManelLoureiro from "@/assets/books/apocalipsis-z-de-manel-loureiro.jpeg";
import apocalipsisZLaIraDeLosJustosDeManelLoureiro from "@/assets/books/apocalipsis-z-la-ira-de-los-justos-de-manel-loureiro.jpeg";
import apocalipsisZLosDiasOscurosDeManelLoureiro from "@/assets/books/apocalipsis-z-los-dias-oscuros-de-manel-loureiro.jpeg";
import area81DeStephenKing from "@/assets/books/area-81-de-stephen-king.jpeg";
import bajoLaMismaEstrellaDeJohnGreen from "@/assets/books/bajo-la-misma-estrella-de-john-green.jpg";
import blancanievesDeJacobYWilhelmGrimm from "@/assets/books/blancanieves-de-jacob-y-wilhelm-grimm.jpg";
import buenosPresagiosDeNeilGaimanYTerryPratchett from "@/assets/books/buenos-presagios-de-neil-gaiman-y-terry-pratchett.jpg";
import cajaNegraDeFranciscoNarla from "@/assets/books/caja-negra-de-francisco-narla.jpg";
import carmillaDeJosephSheridanLeFanu from "@/assets/books/carmilla-de-joseph-sheridan-le-fanu.jpg";
import carrieDeStephenKing from "@/assets/books/carrie-de-stephen-king.jpg";
import circulosInfernalesDeAaVv from "@/assets/books/circulos-infernales-de-aa-vv.jpg";
import ciudadDeHuesoDeCassandraClare from "@/assets/books/ciudad-de-hueso-de-cassandra-clare.jpg";
import colegioZAlaEsteDeIgnacioMallen from "@/assets/books/colegio-z-ala-este-de-ignacio-mallen.jpg";
import contraElVientoDelNorteDeDanielGlattauer from "@/assets/books/contra-el-viento-del-norte-de-daniel-glattauer.jpg";
import cosasRarasQueSeOyenEnLasLibreriasDeJenCampbell from "@/assets/books/cosas-raras-que-se-oyen-en-las-librerias-de-jen-campbell.jpg";
import cuentosDeNavidadCharlesDickens from "@/assets/books/cuentos-de-navidad-charles-dickens.jpg";
import cuentosInconclusosDeNumenorYLaTierraMediaDeJohnRonaldReuelTolkien from "@/assets/books/cuentos-inconclusos-de-numenor-y-la-tierra-media-de-john-ronald-reuel-tolkien.jpg";
import cyranoDeBergeracDeEdmondRostand from "@/assets/books/cyrano-de-bergerac-de-edmond-rostand.jpg";
import deQueHabloCuandoHabloDeCorrerDeHarukiMurakami from "@/assets/books/de-que-hablo-cuando-hablo-de-correr-de-haruki-murakami.jpg";
import deUnaVidaAOtraDeFernandoDelgado from "@/assets/books/de-una-vida-a-otra-de-fernando-delgado.jpg";
import diezNegritosDeAgathaChristie from "@/assets/books/diez-negritos-de-agatha-christie.jpg";
import divergenteDeVeronicaRoth from "@/assets/books/divergente-de-veronica-roth.jpg";
import donQuijoteDeLaManchaMiguelDeCervantes from "@/assets/books/don-quijote-de-la-mancha-miguel-de-cervantes.jpg";
import dondeEstaElLimiteDeJosefAjram from "@/assets/books/donde-esta-el-limite-de-josef-ajram.jpg";
import edenInterrumpidoDeCarlosSisi from "@/assets/books/eden-interrumpido-de-carlos-sisi.jpg";
import elAmanteJaponesDeIsabelAllende from "@/assets/books/el-amante-japones-de-isabel-allende.jpg";
import elArcaDeSchindlerDeThomasKeneally from "@/assets/books/el-arca-de-schindler-de-thomas-keneally.jpg";
import elBosqueDeLosInocentesDeGraziellaMoreno from "@/assets/books/el-bosque-de-los-inocentes-de-graziella-moreno.jpg";
import elBunkerDeNoeDeGabriRodenas from "@/assets/books/el-bunker-de-noe-de-gabri-rodenas.jpeg";
import elCicloDelHombreLoboDeStephenKing from "@/assets/books/el-ciclo-del-hombre-lobo-de-stephen-king.jpg";
import elClubDeLaLuchaDeChuckPalahniuk from "@/assets/books/el-club-de-la-lucha-de-chuck-palahniuk.jpg";
import elColeccionistaDeRelojesExtraordinariosDeLauraGallego from "@/assets/books/el-coleccionista-de-relojes-extraordinarios-de-laura-gallego.jpg";
import elColorDeLaMagiaTerryPratchett from "@/assets/books/el-color-de-la-magia-terry-pratchett.jpg";
import elCondeDeMontecristoDeAlexandreDumas from "@/assets/books/el-conde-de-montecristo-de-alexandre-dumas.jpg";
import elCuriosoCasoDeBenjaminButtonDeFScottFitzgerald from "@/assets/books/el-curioso-caso-de-benjamin-button-de-f-scott-fitzgerald.jpg";
import elDiarioDeBridgetJonesDeHelenFielding from "@/assets/books/el-diario-de-bridget-jones-de-helen-fielding.jpg";
import elExorcistaDeWilliamPeterBlatty from "@/assets/books/el-exorcista-de-william-peter-blatty.jpg";
import elExtranoCasoDelDrJekyllYMrHydeDeRobertLouisStevenson from "@/assets/books/el-extrano-caso-del-dr-jekyll-y-mr-hyde-de-robert-louis-stevenson.jpg";
import elFantasmaDeCantervilleDeOscarWilde from "@/assets/books/el-fantasma-de-canterville-de-oscar-wilde.jpeg";
import elGranGatsbyDeFrancisScottFitzgerald from "@/assets/books/el-gran-gatsby-de-francis-scott-fitzgerald.jpg";
import elHobbitDeJohnRonaldReuelTolkien from "@/assets/books/el-hobbit-de-john-ronald-reuel-tolkien.jpg";
import elHombreInvisibleDeHGWells from "@/assets/books/el-hombre-invisible-de-h-g-wells.jpg";
import elHombreQueArreglabaLasBicicletasDeAngelGilCheza from "@/assets/books/el-hombre-que-arreglaba-las-bicicletas-de-angel-gil-cheza.jpg";
import elHorrorDeDunwichDeHPLovecraft from "@/assets/books/el-horror-de-dunwich-de-h-p-lovecraft.jpg";
import elLibroProhibidoDeChristianJacq from "@/assets/books/el-libro-prohibido-de-christian-jacq.jpg";
import elMisterioDeSalemsLotDeStephenKing from "@/assets/books/el-misterio-de-salems-lot-de-stephen-king.jpg";
import elMisteriosoCasoDeStylesAgathaChristie from "@/assets/books/el-misterioso-caso-de-styles-agatha-christie.jpg";
import elMonteDeLasAnimasDeGustavoAdolfoBecquer from "@/assets/books/el-monte-de-las-animas-de-gustavo-adolfo-becquer.jpg";
import elNinoConElPijamaDeRayasDeJohnBoyne from "@/assets/books/el-nino-con-el-pijama-de-rayas-de-john-boyne.jpg";
import elNombreDelVientoDePatrickRothfuss from "@/assets/books/el-nombre-del-viento-de-patrick-rothfuss.jpg";
import elPrincipitoDeAntoineDeSaintExupery from "@/assets/books/el-principito-de-antoine-de-saint-exupery.jpeg";
import elResplandorDeStephenKing from "@/assets/books/el-resplandor-de-stephen-king.jpg";
import elRetornoDelReyDeJohnRonaldReuelTolkien from "@/assets/books/el-retorno-del-rey-de-john-ronald-reuel-tolkien.jpg";
import elSenorDeLasMoscasWilliamGolding from "@/assets/books/el-senor-de-las-moscas-william-golding.jpg";
import elSilencioDeLaCiudadBlancaEvaGarciaSaenzDeUrturi from "@/assets/books/el-silencio-de-la-ciudad-blanca-eva-garcia-saenz-de-urturi.jpg";
import elSilmarillionDeJohnRonaldReuelTolkien from "@/assets/books/el-silmarillion-de-john-ronald-reuel-tolkien.jpeg";
import elUmbralDeLaNocheStephenKing from "@/assets/books/el-umbral-de-la-noche-stephen-king.jpg";
import elValleDeLosLobosDeLauraGallego from "@/assets/books/el-valle-de-los-lobos-de-laura-gallego.jpg";
import elVampiroDeJohnWilliamPolidori from "@/assets/books/el-vampiro-de-john-william-polidori.jpg";
import elZorroDeIsabelAllende from "@/assets/books/el-zorro-de-isabel-allende.jpg";
import fahrenheit451DeRayBradbury from "@/assets/books/fahrenheit-451-de-ray-bradbury.jpg";
import finisMundiDeLauraGallego from "@/assets/books/finis-mundi-de-laura-gallego.jpg";
import flashforwardDeRobertJSawyer from "@/assets/books/flashforward-de-robert-j-sawyer.jpg";
import floresParaAlgernonDeDanielKeyes from "@/assets/books/flores-para-algernon-de-daniel-keyes.jpg";
import frankensteinDeMaryShelley from "@/assets/books/frankenstein-de-mary-shelley.jpg";
import fulgorDeManelLoureiro from "@/assets/books/fulgor-de-manel-loureiro.jpg";
import genesisDeBernardBeckett from "@/assets/books/genesis-de-bernard-beckett.jpg";
import guerraMundialZDeMaxBrooks from "@/assets/books/guerra-mundial-z-de-max-brooks.jpg";
import harryPotterYElCalizDeFuegoJKRowling from "@/assets/books/harry-potter-y-el-caliz-de-fuego-j-k-rowling.jpg";
import harryPotterYElPrisioneroDeAzkabanJKRowling from "@/assets/books/harry-potter-y-el-prisionero-de-azkaban-j-k-rowling.jpg";
import harryPotterYLaCamaraSecretaDeJKRowling from "@/assets/books/harry-potter-y-la-camara-secreta-de-j-k-rowling.jpg";
import harryPotterYLaOrdenDelFenixDeJKRowling from "@/assets/books/harry-potter-y-la-orden-del-fenix-de-j-k-rowling.jpg";
import harryPotterYLaPiedraFilosofalDeJKRowling from "@/assets/books/harry-potter-y-la-piedra-filosofal-de-j-k-rowling.jpg";
import historiasMinusculasDeBettiePathway from "@/assets/books/historias-minusculas-de-bettie-pathway.jpg";
import houseOfCardsDeMichaelDobbs from "@/assets/books/house-of-cards-de-michael-dobbs.jpg";
import aliciaReina from "@/assets/books/inline/alicia-reina.jpg";
import crowley from "@/assets/books/inline/crowley.jpg";
import gatoCheshire from "@/assets/books/inline/gato-cheshire.jpg";
import lcBridgetJones from "@/assets/books/inline/LC-bridget-jones.jpg";
import musicaClasicaInstrumental from "@/assets/books/inline/musica-clasica-instrumental.jpg";
import peterPanIlustracion from "@/assets/books/inline/peter-pan-ilustracion.jpg";
import puntuacionPatos from "@/assets/books/inline/puntuacion-patos.png";
import instrumentalDeJamesRhodes from "@/assets/books/instrumental-de-james-rhodes.jpg";
import insurgenteDeVeronicaRoth from "@/assets/books/insurgente-de-veronica-roth.jpg";
import juegoDeTronosDeGeorgeRRMartin from "@/assets/books/juego-de-tronos-de-george-r-r-martin.jpg";
import kallocainaDeKarinBoye from "@/assets/books/kallocaina-de-karin-boye.jpg";
import laAventuraDeCorrerDescalzoDeEmilioSaezSoro from "@/assets/books/la-aventura-de-correr-descalzo-de-emilio-saez-soro.jpg";
import laCasaDeLaMuerteDeRLStine from "@/assets/books/la-casa-de-la-muerte-de-r-l-stine.jpg";
import laCasaDelCrepusculoDeLauraGallego from "@/assets/books/la-casa-del-crepusculo-de-laura-gallego.jpg";
import laComunidadDelAnilloDeJohnRonaldReuelTolkien from "@/assets/books/la-comunidad-del-anillo-de-john-ronald-reuel-tolkien.jpg";
import laCondesaSangrientaDeAlejandraPizarnik from "@/assets/books/la-condesa-sangrienta-de-alejandra-pizarnik.jpg";
import laGuerraCivilContadaALosJovenesDeArturoPerezReverte from "@/assets/books/la-guerra-civil-contada-a-los-jovenes-de-arturo-perez-reverte.jpg";
import laIslaDeAliceDanielSanchezArevalo from "@/assets/books/la-isla-de-alice-daniel-sanchez-arevalo.jpg";
import laLadronaDeLibrosDeMarkusZusak from "@/assets/books/la-ladrona-de-libros-de-markus-zusak.jpg";
import laLeyendaDeSleepyHollowDeWashingtonIrving from "@/assets/books/la-leyenda-de-sleepy-hollow-de-washington-irving.jpg";
import laMaldicionDelMaestroDeLauraGallego from "@/assets/books/la-maldicion-del-maestro-de-laura-gallego.jpg";
import laMarchaZombiDeMaxBrooks from "@/assets/books/la-marcha-zombi-de-max-brooks.jpg";
import laMetamorfosisDeFranzKafka from "@/assets/books/la-metamorfosis-de-franz-kafka.jpg";
import laMujerDeNegroDeSusanHill from "@/assets/books/la-mujer-de-negro-de-susan-hill.jpg";
import laPrincesaDeHieloCamillaLackberg from "@/assets/books/la-princesa-de-hielo-camilla-lackberg.jpg";
import laProfeciaDeDavidSeltzer from "@/assets/books/la-profecia-de-david-seltzer.jpg";
import laSemillaDelDiabloDeIraLevin from "@/assets/books/la-semilla-del-diablo-de-ira-levin.jpg";
import laSombraDelVientoDeCarlosRuizZafon from "@/assets/books/la-sombra-del-viento-de-carlos-ruiz-zafon.jpg";
import laTumbaMalditaDeChristianJacq from "@/assets/books/la-tumba-maldita-de-christian-jacq.jpg";
import lasBrujasDeRoaldDahl from "@/assets/books/las-brujas-de-roald-dahl.jpg";
import lasDosTorresDeJohnRonaldReuelTolkien from "@/assets/books/las-dos-torres-de-john-ronald-reuel-tolkien.jpg";
import lasHijasDeTaraDeLauraGallego from "@/assets/books/las-hijas-de-tara-de-laura-gallego.jpg";
import lealDeVeronicaRoth from "@/assets/books/leal-de-veronica-roth.jpg";
import losAnosDePeregrinacionDelChicoSinColorDeHarukiMurakami from "@/assets/books/los-anos-de-peregrinacion-del-chico-sin-color-de-haruki-murakami.jpg";
import losBesosEnElPanDeAlmudenaGrandes from "@/assets/books/los-besos-en-el-pan-de-almudena-grandes.jpg";
import losCrimenesDeLaRueMorgueYOtrosDeEdgarAllanPoe from "@/assets/books/los-crimenes-de-la-rue-morgue-y-otros-de-edgar-allan-poe.jpg";
import losEspantapajarosAndanAMedianocheDeRLStine from "@/assets/books/los-espantapajaros-andan-a-medianoche-de-r-l-stine.jpg";
import losGuardianesDeLaHistoriaDeElisabettaCametti from "@/assets/books/los-guardianes-de-la-historia-de-elisabetta-cametti.jpg";
import losRitosDelAguaEvaGarciaSaenzDeUrturi from "@/assets/books/los-ritos-del-agua-eva-garcia-saenz-de-urturi.jpg";
import lucesEnElMarDeMiquelReina from "@/assets/books/luces-en-el-mar-de-miquel-reina.jpg";
import mindTheGapDeNachoIribarnegaray from "@/assets/books/mind-the-gap-de-nacho-iribarnegaray.jpg";
import momoDeMichaelEnde from "@/assets/books/momo-de-michael-ende.jpg";
import mrMercedesDeStephenKing from "@/assets/books/mr-mercedes-de-stephen-king.jpg";
import nacidosParaCorrerDeChristopherMcdougall from "@/assets/books/nacidos-para-correr-de-christopher-mcdougall.jpg";
import nieblaDeMiguelDeUnamuno from "@/assets/books/niebla-de-miguel-de-unamuno.jpg";
import noBajesAlSotanoDeRLStine from "@/assets/books/no-bajes-al-sotano-de-r-l-stine.jpg";
import noSeDondeEstaElLimitePeroSiSeDondeNoEstaDeJosefAjram from "@/assets/books/no-se-donde-esta-el-limite-pero-si-se-donde-no-esta-de-josef-ajram.jpg";
import novelaDeAjedrezDeStefanZweig from "@/assets/books/novela-de-ajedrez-de-stefan-zweig.jpg";
import ojalaFueraCiertoDeMarcLevy from "@/assets/books/ojala-fuera-cierto-de-marc-levy.jpg";
import oscuroDeTeoRodriguez from "@/assets/books/oscuro-de-teo-rodriguez.jpg";
import otraVidaDeSJWatson from "@/assets/books/otra-vida-de-s-j-watson.jpg";
import peligroEnLasProfundidadesDeRLStine from "@/assets/books/peligro-en-las-profundidades-de-r-l-stine.jpg";
import peterPanDeJamesMBarrie from "@/assets/books/peter-pan-de-james-m-barrie.jpg";
import pidelePapelesASantaDeSimpaMartinYZekeOchoa from "@/assets/books/pidele-papeles-a-santa-de-simpa-martin-y-zeke-ochoa.jpg";
import ponteEnFormaEn9SemanasYMediaDeJuanRallo from "@/assets/books/ponte-en-forma-en-9-semanas-y-media-de-juan-rallo.jpg";
import prontoSeraDeNocheDeJesusCanadas from "@/assets/books/pronto-sera-de-noche-de-jesus-canadas.jpg";
import rabiaDeStephenKing from "@/assets/books/rabia-de-stephen-king.jpg";
import retornoALaIslaBlancaDeLauraGallego from "@/assets/books/retorno-a-la-isla-blanca-de-laura-gallego.jpg";
import revivalDeStephenKing from "@/assets/books/revival-de-stephen-king.jpg";
import soyLeyendaDeRichardMatheson from "@/assets/books/soy-leyenda-de-richard-matheson.jpg";
import steveJobsLaBiografiaDeWalterIsaacson from "@/assets/books/steve-jobs-la-biografia-de-walter-isaacson.jpg";
import suenanLosAndroidesConOvejasElectricasDePhilipKDick from "@/assets/books/suenan-los-androides-con-ovejas-electricas-de-philip-k-dick.jpg";
import tienesHastaLas10DeFranciscoCastro from "@/assets/books/tienes-hasta-las-10-de-francisco-castro.jpg";
import todoEstoTeDareDeDoloresRedondo from "@/assets/books/todo-esto-te-dare-de-dolores-redondo.jpg";
import unDiaEnHorrorlandiaDeRLStine from "@/assets/books/un-dia-en-horrorlandia-de-r-l-stine.jpg";
import unMonstruoVieneAVermeDePatrickNess from "@/assets/books/un-monstruo-viene-a-verme-de-patrick-ness.jpg";
import unMundoFelizDeAldousHuxley from "@/assets/books/un-mundo-feliz-de-aldous-huxley.jpg";
import unaEdadDificilDeAnnaStarobinets from "@/assets/books/una-edad-dificil-de-anna-starobinets.jpg";
import unaHistoriaDeLaGuerraCivilQueNoVaAGustarANadieJuanEslavaGalan from "@/assets/books/una-historia-de-la-guerra-civil-que-no-va-a-gustar-a-nadie-juan-eslava-galan.jpg";
import veinticuatroHorasEnLaVidaDeUnaMujerStefanZweig from "@/assets/books/veinticuatro-horas-en-la-vida-de-una-mujer-stefan-zweig.jpg";
import yoNoLaMateDeFernandoTrujillo from "@/assets/books/yo-no-la-mate-de-fernando-trujillo.jpg";
import bookDefaultEn from "@/assets/defaults/book-default-en.jpg";
import bookDefaultEs from "@/assets/defaults/book-default-es.jpg";
import postDefault from "@/assets/defaults/post-default.jpg";
import tutorialDefault from "@/assets/defaults/tutorial-default.jpg";
import cabeceraHistoriaInformatica from "@/assets/posts/cabecera-historia-informatica.jpg";
import cabeceraProgramacionCurso from "@/assets/posts/cabecera-programacion-curso.jpg";
import cabeceraVimPost from "@/assets/posts/cabecera-vim-post.jpg";
import cabeceraApple from "@/assets/tutorials/cabecera-apple.jpg";
import cabeceraGitCurso from "@/assets/tutorials/cabecera-git-curso.jpg";
import cabeceraGit from "@/assets/tutorials/cabecera-git.jpg";
import cabeceraLinux from "@/assets/tutorials/cabecera-linux.jpg";
import cabeceraPythonCurso from "@/assets/tutorials/cabecera-python-curso.jpg";
import cabeceraVimCurso from "@/assets/tutorials/cabecera-vim-curso.jpg";
import cabeceraWindows from "@/assets/tutorials/cabecera-windows.jpg";
import clonandoRepositorioGithub from "@/assets/tutorials/inline/clonando-repositorio-github.jpeg";
import creandoRepositorioGithub from "@/assets/tutorials/inline/creando-repositorio-github.jpeg";
import nuestroNuevoRepositorioGithub from "@/assets/tutorials/inline/nuestro-nuevo-repositorio-github.jpeg";
import nuevoRepositorioGithub from "@/assets/tutorials/inline/nuevo-repositorio-github.jpeg";
import repositorioGithubCreado from "@/assets/tutorials/inline/repositorio-github-creado.jpeg";
import seccionTagsGithub from "@/assets/tutorials/inline/seccion-tags-github.jpeg";
import { getDefaultLanguageCode, type LanguageKey } from "@/config/languages";

/**
 * Book Cover Images Map
 *
 * Key: Image filename (without extension) - matches the filename in content frontmatter
 * Value: Imported ImageMetadata
 *
 * Usage:
 * ```astro
 * import { bookCovers } from '@/utils/imageImports';
 * <OptimizedImage src={bookCovers['1984-de-george-orwell']} alt="..." />
 * ```
 */
export const bookCovers: Record<string, ImageMetadata> = {
  "1984-de-george-orwell": book1984DeGeorgeOrwell,
  "alicia-en-el-pais-de-las-maravillas-lewis-carroll-edicion-conmemorativa":
    aliciaEnElPaisDeLasMaravillasLewisCarrollEdicionConmemorativa,
  "alicia-en-el-pais-de-las-maravillas-lewis-carroll": aliciaEnElPaisDeLasMaravillasLewisCarroll,
  "apocalipsis-de-stephen-king": apocalipsisDeStephenKing,
  "apocalipsis-z-de-manel-loureiro": apocalipsisZDeManelLoureiro,
  "apocalipsis-z-la-ira-de-los-justos-de-manel-loureiro": apocalipsisZLaIraDeLosJustosDeManelLoureiro,
  "apocalipsis-z-los-dias-oscuros-de-manel-loureiro": apocalipsisZLosDiasOscurosDeManelLoureiro,
  "area-81-de-stephen-king": area81DeStephenKing,
  "bajo-la-misma-estrella-de-john-green": bajoLaMismaEstrellaDeJohnGreen,
  "blancanieves-de-jacob-y-wilhelm-grimm": blancanievesDeJacobYWilhelmGrimm,
  "buenos-presagios-de-neil-gaiman-y-terry-pratchett": buenosPresagiosDeNeilGaimanYTerryPratchett,
  "caja-negra-de-francisco-narla": cajaNegraDeFranciscoNarla,
  "carmilla-de-joseph-sheridan-le-fanu": carmillaDeJosephSheridanLeFanu,
  "carrie-de-stephen-king": carrieDeStephenKing,
  "circulos-infernales-de-aa-vv": circulosInfernalesDeAaVv,
  "ciudad-de-hueso-de-cassandra-clare": ciudadDeHuesoDeCassandraClare,
  "colegio-z-ala-este-de-ignacio-mallen": colegioZAlaEsteDeIgnacioMallen,
  "contra-el-viento-del-norte-de-daniel-glattauer": contraElVientoDelNorteDeDanielGlattauer,
  "cosas-raras-que-se-oyen-en-las-librerias-de-jen-campbell": cosasRarasQueSeOyenEnLasLibreriasDeJenCampbell,
  "cuentos-de-navidad-charles-dickens": cuentosDeNavidadCharlesDickens,
  "cuentos-inconclusos-de-numenor-y-la-tierra-media-de-john-ronald-reuel-tolkien":
    cuentosInconclusosDeNumenorYLaTierraMediaDeJohnRonaldReuelTolkien,
  "cyrano-de-bergerac-de-edmond-rostand": cyranoDeBergeracDeEdmondRostand,
  "de-que-hablo-cuando-hablo-de-correr-de-haruki-murakami": deQueHabloCuandoHabloDeCorrerDeHarukiMurakami,
  "de-una-vida-a-otra-de-fernando-delgado": deUnaVidaAOtraDeFernandoDelgado,
  "diez-negritos-de-agatha-christie": diezNegritosDeAgathaChristie,
  "divergente-de-veronica-roth": divergenteDeVeronicaRoth,
  "don-quijote-de-la-mancha-miguel-de-cervantes": donQuijoteDeLaManchaMiguelDeCervantes,
  "donde-esta-el-limite-de-josef-ajram": dondeEstaElLimiteDeJosefAjram,
  "eden-interrumpido-de-carlos-sisi": edenInterrumpidoDeCarlosSisi,
  "el-amante-japones-de-isabel-allende": elAmanteJaponesDeIsabelAllende,
  "el-arca-de-schindler-de-thomas-keneally": elArcaDeSchindlerDeThomasKeneally,
  "el-bosque-de-los-inocentes-de-graziella-moreno": elBosqueDeLosInocentesDeGraziellaMoreno,
  "el-bunker-de-noe-de-gabri-rodenas": elBunkerDeNoeDeGabriRodenas,
  "el-ciclo-del-hombre-lobo-de-stephen-king": elCicloDelHombreLoboDeStephenKing,
  "el-club-de-la-lucha-de-chuck-palahniuk": elClubDeLaLuchaDeChuckPalahniuk,
  "el-coleccionista-de-relojes-extraordinarios-de-laura-gallego": elColeccionistaDeRelojesExtraordinariosDeLauraGallego,
  "el-color-de-la-magia-terry-pratchett": elColorDeLaMagiaTerryPratchett,
  "el-conde-de-montecristo-de-alexandre-dumas": elCondeDeMontecristoDeAlexandreDumas,
  "el-curioso-caso-de-benjamin-button-de-f-scott-fitzgerald": elCuriosoCasoDeBenjaminButtonDeFScottFitzgerald,
  "el-diario-de-bridget-jones-de-helen-fielding": elDiarioDeBridgetJonesDeHelenFielding,
  "el-exorcista-de-william-peter-blatty": elExorcistaDeWilliamPeterBlatty,
  "el-extrano-caso-del-dr-jekyll-y-mr-hyde-de-robert-louis-stevenson":
    elExtranoCasoDelDrJekyllYMrHydeDeRobertLouisStevenson,
  "el-fantasma-de-canterville-de-oscar-wilde": elFantasmaDeCantervilleDeOscarWilde,
  "el-gran-gatsby-de-francis-scott-fitzgerald": elGranGatsbyDeFrancisScottFitzgerald,
  "el-hobbit-de-john-ronald-reuel-tolkien": elHobbitDeJohnRonaldReuelTolkien,
  "el-hombre-invisible-de-h-g-wells": elHombreInvisibleDeHGWells,
  "el-hombre-que-arreglaba-las-bicicletas-de-angel-gil-cheza": elHombreQueArreglabaLasBicicletasDeAngelGilCheza,
  "el-horror-de-dunwich-de-h-p-lovecraft": elHorrorDeDunwichDeHPLovecraft,
  "el-libro-prohibido-de-christian-jacq": elLibroProhibidoDeChristianJacq,
  "el-misterio-de-salems-lot-de-stephen-king": elMisterioDeSalemsLotDeStephenKing,
  "el-misterioso-caso-de-styles-agatha-christie": elMisteriosoCasoDeStylesAgathaChristie,
  "el-monte-de-las-animas-de-gustavo-adolfo-becquer": elMonteDeLasAnimasDeGustavoAdolfoBecquer,
  "el-nino-con-el-pijama-de-rayas-de-john-boyne": elNinoConElPijamaDeRayasDeJohnBoyne,
  "el-nombre-del-viento-de-patrick-rothfuss": elNombreDelVientoDePatrickRothfuss,
  "el-principito-de-antoine-de-saint-exupery": elPrincipitoDeAntoineDeSaintExupery,
  "el-resplandor-de-stephen-king": elResplandorDeStephenKing,
  "el-retorno-del-rey-de-john-ronald-reuel-tolkien": elRetornoDelReyDeJohnRonaldReuelTolkien,
  "el-senor-de-las-moscas-william-golding": elSenorDeLasMoscasWilliamGolding,
  "el-silencio-de-la-ciudad-blanca-eva-garcia-saenz-de-urturi": elSilencioDeLaCiudadBlancaEvaGarciaSaenzDeUrturi,
  "el-silmarillion-de-john-ronald-reuel-tolkien": elSilmarillionDeJohnRonaldReuelTolkien,
  "el-umbral-de-la-noche-stephen-king": elUmbralDeLaNocheStephenKing,
  "el-valle-de-los-lobos-de-laura-gallego": elValleDeLosLobosDeLauraGallego,
  "el-vampiro-de-john-william-polidori": elVampiroDeJohnWilliamPolidori,
  "el-zorro-de-isabel-allende": elZorroDeIsabelAllende,
  "fahrenheit-451-de-ray-bradbury": fahrenheit451DeRayBradbury,
  "finis-mundi-de-laura-gallego": finisMundiDeLauraGallego,
  "flashforward-de-robert-j-sawyer": flashforwardDeRobertJSawyer,
  "flores-para-algernon-de-daniel-keyes": floresParaAlgernonDeDanielKeyes,
  "frankenstein-de-mary-shelley": frankensteinDeMaryShelley,
  "fulgor-de-manel-loureiro": fulgorDeManelLoureiro,
  "genesis-de-bernard-beckett": genesisDeBernardBeckett,
  "guerra-mundial-z-de-max-brooks": guerraMundialZDeMaxBrooks,
  "harry-potter-y-el-caliz-de-fuego-j-k-rowling": harryPotterYElCalizDeFuegoJKRowling,
  "harry-potter-y-el-prisionero-de-azkaban-j-k-rowling": harryPotterYElPrisioneroDeAzkabanJKRowling,
  "harry-potter-y-la-camara-secreta-de-j-k-rowling": harryPotterYLaCamaraSecretaDeJKRowling,
  "harry-potter-y-la-orden-del-fenix-de-j-k-rowling": harryPotterYLaOrdenDelFenixDeJKRowling,
  "harry-potter-y-la-piedra-filosofal-de-j-k-rowling": harryPotterYLaPiedraFilosofalDeJKRowling,
  "historias-minusculas-de-bettie-pathway": historiasMinusculasDeBettiePathway,
  "house-of-cards-de-michael-dobbs": houseOfCardsDeMichaelDobbs,
  "instrumental-de-james-rhodes": instrumentalDeJamesRhodes,
  "insurgente-de-veronica-roth": insurgenteDeVeronicaRoth,
  "juego-de-tronos-de-george-r-r-martin": juegoDeTronosDeGeorgeRRMartin,
  "kallocaina-de-karin-boye": kallocainaDeKarinBoye,
  "la-aventura-de-correr-descalzo-de-emilio-saez-soro": laAventuraDeCorrerDescalzoDeEmilioSaezSoro,
  "la-casa-de-la-muerte-de-r-l-stine": laCasaDeLaMuerteDeRLStine,
  "la-casa-del-crepusculo-de-laura-gallego": laCasaDelCrepusculoDeLauraGallego,
  "la-comunidad-del-anillo-de-john-ronald-reuel-tolkien": laComunidadDelAnilloDeJohnRonaldReuelTolkien,
  "la-condesa-sangrienta-de-alejandra-pizarnik": laCondesaSangrientaDeAlejandraPizarnik,
  "la-guerra-civil-contada-a-los-jovenes-de-arturo-perez-reverte": laGuerraCivilContadaALosJovenesDeArturoPerezReverte,
  "la-isla-de-alice-daniel-sanchez-arevalo": laIslaDeAliceDanielSanchezArevalo,
  "la-ladrona-de-libros-de-markus-zusak": laLadronaDeLibrosDeMarkusZusak,
  "la-leyenda-de-sleepy-hollow-de-washington-irving": laLeyendaDeSleepyHollowDeWashingtonIrving,
  "la-maldicion-del-maestro-de-laura-gallego": laMaldicionDelMaestroDeLauraGallego,
  "la-marcha-zombi-de-max-brooks": laMarchaZombiDeMaxBrooks,
  "la-metamorfosis-de-franz-kafka": laMetamorfosisDeFranzKafka,
  "la-mujer-de-negro-de-susan-hill": laMujerDeNegroDeSusanHill,
  "la-princesa-de-hielo-camilla-lackberg": laPrincesaDeHieloCamillaLackberg,
  "la-profecia-de-david-seltzer": laProfeciaDeDavidSeltzer,
  "la-semilla-del-diablo-de-ira-levin": laSemillaDelDiabloDeIraLevin,
  "la-sombra-del-viento-de-carlos-ruiz-zafon": laSombraDelVientoDeCarlosRuizZafon,
  "la-tumba-maldita-de-christian-jacq": laTumbaMalditaDeChristianJacq,
  "las-brujas-de-roald-dahl": lasBrujasDeRoaldDahl,
  "las-dos-torres-de-john-ronald-reuel-tolkien": lasDosTorresDeJohnRonaldReuelTolkien,
  "las-hijas-de-tara-de-laura-gallego": lasHijasDeTaraDeLauraGallego,
  "leal-de-veronica-roth": lealDeVeronicaRoth,
  "los-anos-de-peregrinacion-del-chico-sin-color-de-haruki-murakami":
    losAnosDePeregrinacionDelChicoSinColorDeHarukiMurakami,
  "los-besos-en-el-pan-de-almudena-grandes": losBesosEnElPanDeAlmudenaGrandes,
  "los-crimenes-de-la-rue-morgue-y-otros-de-edgar-allan-poe": losCrimenesDeLaRueMorgueYOtrosDeEdgarAllanPoe,
  "los-espantapajaros-andan-a-medianoche-de-r-l-stine": losEspantapajarosAndanAMedianocheDeRLStine,
  "los-guardianes-de-la-historia-de-elisabetta-cametti": losGuardianesDeLaHistoriaDeElisabettaCametti,
  "los-ritos-del-agua-eva-garcia-saenz-de-urturi": losRitosDelAguaEvaGarciaSaenzDeUrturi,
  "luces-en-el-mar-de-miquel-reina": lucesEnElMarDeMiquelReina,
  "mind-the-gap-de-nacho-iribarnegaray": mindTheGapDeNachoIribarnegaray,
  "momo-de-michael-ende": momoDeMichaelEnde,
  "mr-mercedes-de-stephen-king": mrMercedesDeStephenKing,
  "nacidos-para-correr-de-christopher-mcdougall": nacidosParaCorrerDeChristopherMcdougall,
  "niebla-de-miguel-de-unamuno": nieblaDeMiguelDeUnamuno,
  "no-bajes-al-sotano-de-r-l-stine": noBajesAlSotanoDeRLStine,
  "no-se-donde-esta-el-limite-pero-si-se-donde-no-esta-de-josef-ajram":
    noSeDondeEstaElLimitePeroSiSeDondeNoEstaDeJosefAjram,
  "novela-de-ajedrez-de-stefan-zweig": novelaDeAjedrezDeStefanZweig,
  "ojala-fuera-cierto-de-marc-levy": ojalaFueraCiertoDeMarcLevy,
  "oscuro-de-teo-rodriguez": oscuroDeTeoRodriguez,
  "otra-vida-de-s-j-watson": otraVidaDeSJWatson,
  "peligro-en-las-profundidades-de-r-l-stine": peligroEnLasProfundidadesDeRLStine,
  "peter-pan-de-james-m-barrie": peterPanDeJamesMBarrie,
  "pidele-papeles-a-santa-de-simpa-martin-y-zeke-ochoa": pidelePapelesASantaDeSimpaMartinYZekeOchoa,
  "ponte-en-forma-en-9-semanas-y-media-de-juan-rallo": ponteEnFormaEn9SemanasYMediaDeJuanRallo,
  "pronto-sera-de-noche-de-jesus-canadas": prontoSeraDeNocheDeJesusCanadas,
  "rabia-de-stephen-king": rabiaDeStephenKing,
  "retorno-a-la-isla-blanca-de-laura-gallego": retornoALaIslaBlancaDeLauraGallego,
  "revival-de-stephen-king": revivalDeStephenKing,
  "soy-leyenda-de-richard-matheson": soyLeyendaDeRichardMatheson,
  "steve-jobs-la-biografia-de-walter-isaacson": steveJobsLaBiografiaDeWalterIsaacson,
  "suenan-los-androides-con-ovejas-electricas-de-philip-k-dick": suenanLosAndroidesConOvejasElectricasDePhilipKDick,
  "tienes-hasta-las-10-de-francisco-castro": tienesHastaLas10DeFranciscoCastro,
  "todo-esto-te-dare-de-dolores-redondo": todoEstoTeDareDeDoloresRedondo,
  "un-dia-en-horrorlandia-de-r-l-stine": unDiaEnHorrorlandiaDeRLStine,
  "un-monstruo-viene-a-verme-de-patrick-ness": unMonstruoVieneAVermeDePatrickNess,
  "un-mundo-feliz-de-aldous-huxley": unMundoFelizDeAldousHuxley,
  "una-edad-dificil-de-anna-starobinets": unaEdadDificilDeAnnaStarobinets,
  "una-historia-de-la-guerra-civil-que-no-va-a-gustar-a-nadie-juan-eslava-galan":
    unaHistoriaDeLaGuerraCivilQueNoVaAGustarANadieJuanEslavaGalan,
  "veinticuatro-horas-en-la-vida-de-una-mujer-stefan-zweig": veinticuatroHorasEnLaVidaDeUnaMujerStefanZweig,
  "yo-no-la-mate-de-fernando-trujillo": yoNoLaMateDeFernandoTrujillo,
};

/**
 * Book Inline Images Map
 *
 * Key: Image filename (without extension) - matches the filename in content frontmatter
 * Value: Imported ImageMetadata
 *
 * Usage:
 * ```astro
 * import { bookInlineImages } from '@/utils/imageImports';
 * <OptimizedImage src={bookInlineImages['alicia-reina']} alt="..." />
 * ```
 */
export const bookInlineImages: Record<string, ImageMetadata> = {
  "alicia-reina": aliciaReina,
  crowley: crowley,
  "gato-cheshire": gatoCheshire,
  "LC-bridget-jones": lcBridgetJones,
  "musica-clasica-instrumental": musicaClasicaInstrumental,
  "peter-pan-ilustracion": peterPanIlustracion,
  "puntuacion-patos": puntuacionPatos,
};

/**
 * Author Picture Images Map
 *
 * Key: Image filename (without extension) - matches the filename in content frontmatter
 * Value: Imported ImageMetadata
 *
 * Usage:
 * ```astro
 * import { authorPictures } from '@/utils/imageImports';
 * <OptimizedImage src={authorPictures['agatha-christie']} alt="..." />
 * ```
 */
export const authorPictures: Record<string, ImageMetadata> = {
  "agatha-christie": agathaChristie,
  "anna-starobinets": annaStarobinets,
  "camilla-lackberg": camillaLackberg,
  "charles-dickens": charlesDickens,
  "dolores-redondo": doloresRedondo,
  "eva-garcia-saenz-de-urturi": evaGarciaSaenzDeUrturi,
  "george-orwell": georgeOrwell,
  "isabel-allende": isabelAllende,
  "j-k-rowling": jKRowling,
  "james-m-barrie": jamesMBarrie,
  "karin-boye": karinBoye,
  "laura-gallego": lauraGallego,
  "martin-zeke-ochoa": martinZekeOchoa,
  "mary-shelley": maryShelley,
  "roald-dahl": roaldDahl,
  "stefan-zweig": stefanZweig,
  "stephen-king": stephenKing,
  "william-golding": williamGolding,
};

/**
 * Default Images Map
 *
 * Fallback images when content doesn't specify a cover/picture
 *
 * Usage:
 * ```astro
 * import { defaultImages } from '@/utils/imageImports';
 * <OptimizedImage src={defaultImages.postDefault} alt="Default post cover" />
 * ```
 */
export const defaultImages = {
  bookDefaultEn,
  bookDefaultEs,
  postDefault,
  tutorialDefault,
};

/**
 * Tutorial Cover Images Map
 *
 * Key: Image filename (without extension) - matches the filename in content frontmatter
 * Value: Imported ImageMetadata
 *
 * Usage:
 * ```astro
 * import { tutorialCovers } from '@/utils/imageImports';
 * <OptimizedImage src={tutorialCovers['cabecera-apple']} alt="..." />
 * ```
 */
export const tutorialCovers: Record<string, ImageMetadata> = {
  "cabecera-apple": cabeceraApple,
  "cabecera-git-curso": cabeceraGitCurso,
  "cabecera-git": cabeceraGit,
  "cabecera-linux": cabeceraLinux,
  "cabecera-python-curso": cabeceraPythonCurso,
  "cabecera-vim-curso": cabeceraVimCurso,
  "cabecera-windows": cabeceraWindows,
};

/**
 * Tutorial Inline Images Map
 *
 * Key: Image filename (without extension) - matches the filename in content frontmatter
 * Value: Imported ImageMetadata
 *
 * Usage:
 * ```astro
 * import { tutorialInlineImages } from '@/utils/imageImports';
 * <OptimizedImage src={tutorialInlineImages['clonando-repositorio-github']} alt="..." />
 * ```
 */
export const tutorialInlineImages: Record<string, ImageMetadata> = {
  "clonando-repositorio-github": clonandoRepositorioGithub,
  "creando-repositorio-github": creandoRepositorioGithub,
  "nuestro-nuevo-repositorio-github": nuestroNuevoRepositorioGithub,
  "nuevo-repositorio-github": nuevoRepositorioGithub,
  "repositorio-github-creado": repositorioGithubCreado,
  "seccion-tags-github": seccionTagsGithub,
};

/**
 * Post Cover Images Map
 *
 * Key: Image filename (without extension) - matches the filename in content frontmatter
 * Value: Imported ImageMetadata
 *
 * Usage:
 * ```astro
 * import { postCovers } from '@/utils/imageImports';
 * <OptimizedImage src={postCovers['cabecera-historia-informatica']} alt="..." />
 * ```
 */
export const postCovers: Record<string, ImageMetadata> = {
  "cabecera-historia-informatica": cabeceraHistoriaInformatica,
  "cabecera-programacion-curso": cabeceraProgramacionCurso,
  "cabecera-vim-post": cabeceraVimPost,
};

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

/**
 * Get a book cover by filename (without path or extension)
 *
 * @param coverPath - Path from content frontmatter (e.g., "/images/books/example.jpg")
 * @param lang - Language for default cover fallback
 * @returns ImageMetadata for optimized rendering
 *
 * @example
 * const cover = getBookCoverImage('/images/books/example.jpg', 'es');
 * <OptimizedImage src={cover} alt="..." />
 */
export function getBookCoverImage(
  coverPath: string | undefined,
  lang: LanguageKey = getDefaultLanguageCode(),
): ImageMetadata {
  if (!coverPath) {
    return lang === getDefaultLanguageCode() ? defaultImages.bookDefaultEs : defaultImages.bookDefaultEn;
  }

  // Extract filename from path: "/images/books/el-hobbit.jpg" -> "el-hobbit"
  const filename = coverPath
    .split("/")
    .pop()
    ?.replace(/\.(jpg|jpeg|png|webp)$/i, "");

  if (!filename || !bookCovers[filename]) {
    console.warn(`Book cover not found: ${coverPath} (filename: ${filename})`);
    return lang === getDefaultLanguageCode() ? defaultImages.bookDefaultEs : defaultImages.bookDefaultEn;
  }

  return bookCovers[filename];
}

/**
 * Get a booksInlin cover by filename (without path or extension)
 *
 * @param coverPath - Path from content frontmatter (e.g., "/images/booksInline/example.jpg")
 * @returns ImageMetadata for optimized rendering
 *
 * @example
 * const cover = getBookInlineImage('/images/booksInline/example.jpg');
 * <OptimizedImage src={cover} alt="..." />
 */
export function getBookInlineImage(coverPath: string | undefined): ImageMetadata {
  if (!coverPath) {
    return defaultImages.postDefault;
  }

  // Extract filename from path: "/images/books/el-hobbit.jpg" -> "el-hobbit"
  const filename = coverPath
    .split("/")
    .pop()
    ?.replace(/\.(jpg|jpeg|png|webp)$/i, "");

  if (!filename || !bookInlineImages[filename]) {
    console.warn(`BooksInlin cover not found: ${coverPath} (filename: ${filename})`);
    return defaultImages.postDefault;
  }

  return bookInlineImages[filename];
}

/**
 * Get a author picture by filename (without path or extension)
 *
 * @param picturePath - Path from content frontmatter (e.g., "/images/authors/example.jpg")
 * @returns ImageMetadata for optimized rendering
 *
 * @example
 * const picture = getAuthorPictureImage('/images/authors/example.jpg');
 * <OptimizedImage src={picture} alt="..." />
 */
export function getAuthorPictureImage(picturePath: string | undefined): ImageMetadata | undefined {
  if (!picturePath) {
    return undefined;
  }

  // If it's a full path, extract filename
  const slug = picturePath.includes("/")
    ? picturePath
        .split("/")
        .pop()
        ?.replace(/\.(jpg|jpeg|png|webp)$/i, "")
    : picturePath;

  if (!slug || !authorPictures[slug]) {
    console.warn(`Author picture not found: ${picturePath} (slug: ${slug})`);
    return undefined;
  }

  return authorPictures[slug];
}

/**
 * Get a tutorial cover by filename (without path or extension)
 *
 * @param coverPath - Path from content frontmatter (e.g., "/images/tutorials/example.jpg")
 * @returns ImageMetadata for optimized rendering
 *
 * @example
 * const cover = getTutorialCoverImage('/images/tutorials/example.jpg');
 * <OptimizedImage src={cover} alt="..." />
 */
export function getTutorialCoverImage(coverPath: string | undefined): ImageMetadata {
  if (!coverPath) {
    return defaultImages.tutorialDefault;
  }

  // Extract filename from path: "/images/books/el-hobbit.jpg" -> "el-hobbit"
  const filename = coverPath
    .split("/")
    .pop()
    ?.replace(/\.(jpg|jpeg|png|webp)$/i, "");

  if (!filename || !tutorialCovers[filename]) {
    console.warn(`Tutorial cover not found: ${coverPath} (filename: ${filename})`);
    return defaultImages.tutorialDefault;
  }

  return tutorialCovers[filename];
}

/**
 * Get a tutorialsInlin cover by filename (without path or extension)
 *
 * @param coverPath - Path from content frontmatter (e.g., "/images/tutorialsInline/example.jpg")
 * @returns ImageMetadata for optimized rendering
 *
 * @example
 * const cover = getTutorialInlineImage('/images/tutorialsInline/example.jpg');
 * <OptimizedImage src={cover} alt="..." />
 */
export function getTutorialInlineImage(coverPath: string | undefined): ImageMetadata {
  if (!coverPath) {
    return defaultImages.postDefault;
  }

  // Extract filename from path: "/images/books/el-hobbit.jpg" -> "el-hobbit"
  const filename = coverPath
    .split("/")
    .pop()
    ?.replace(/\.(jpg|jpeg|png|webp)$/i, "");

  if (!filename || !tutorialInlineImages[filename]) {
    console.warn(`TutorialsInlin cover not found: ${coverPath} (filename: ${filename})`);
    return defaultImages.postDefault;
  }

  return tutorialInlineImages[filename];
}

/**
 * Get a post cover by filename (without path or extension)
 *
 * @param coverPath - Path from content frontmatter (e.g., "/images/posts/example.jpg")
 * @returns ImageMetadata for optimized rendering
 *
 * @example
 * const cover = getPostCoverImage('/images/posts/example.jpg');
 * <OptimizedImage src={cover} alt="..." />
 */
export function getPostCoverImage(coverPath: string | undefined): ImageMetadata {
  if (!coverPath) {
    return defaultImages.postDefault;
  }

  // Extract filename from path: "/images/books/el-hobbit.jpg" -> "el-hobbit"
  const filename = coverPath
    .split("/")
    .pop()
    ?.replace(/\.(jpg|jpeg|png|webp)$/i, "");

  if (!filename || !postCovers[filename]) {
    console.warn(`Post cover not found: ${coverPath} (filename: ${filename})`);
    return defaultImages.postDefault;
  }

  return postCovers[filename];
}

// ============================================================================
// UTILITIES
// ============================================================================

/**
 * Get all available book cover keys
 * Useful for validation or listing
 */
export function getAvailableBookCovers(): string[] {
  return Object.keys(bookCovers);
}

/**
 * Get all available author picture keys
 * Useful for validation or listing
 */
export function getAvailableAuthorPictures(): string[] {
  return Object.keys(authorPictures);
}

/**
 * Check if a book cover exists
 *
 * @param coverPath - Path or slug to check
 * @returns true if the cover exists in the imports
 */
export function hasBookCover(coverPath: string): boolean {
  const filename = coverPath
    .split("/")
    .pop()
    ?.replace(/\.(jpg|jpeg|png|webp)$/i, "");
  return !!filename && !!bookCovers[filename];
}

/**
 * Check if an author picture exists
 *
 * @param slug - Author slug to check
 * @returns true if the picture exists in the imports
 */
export function hasAuthorPicture(slug: string): boolean {
  const authorSlug = slug
    .split("/")
    .pop()
    ?.replace(/\.(jpg|jpeg|png|webp)$/i, "");
  return !!authorSlug && !!authorPictures[authorSlug];
}
