version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    default_reviewers:
      - "fjpalacios"
    default_assignees:
      - "fjpalacios"
    commit_message:
      prefix: "chore"
      include_scope: true
  - package_manager: "docker"
    directory: "/"
    update_schedule: "daily"
    default_reviewers:
      - "fjpalacios"
    default_assignees:
      - "fjpalacios"
    commit_message:
      prefix: "chore"
      include_scope: true
