name: Build Docker image
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: docker/build-push-action@v1
        with:
          repository: fjpalacios/website
          push: false
