name: Push Docker image
on:
  push:
    branches:
      - master
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t fjpalacios/website:latest .
      - name: Login into Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker image
        run: docker push fjpalacios/website:latest
