name: Run Test Suites
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn install --pure-lockfile
      - run: yarn lint
      - run: yarn test
      - run: yarn test:e2e:ci
